---
Name: foxy-feed-routes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'foxy//$Action/$ID/$Name': Dynamic\Foxy\Parser\Controller\FoxyController

---
Only:
  environment: 'dev'
---
SilverStripe\Control\Director:
  rules:
    'foxytest//$Action/$ID/$Name': Dynamic\Foxy\Parser\Tests\Controller\DataTestController
